
# GitHub Pages configuration
title: P2P Bulletin Board Documentation
description: Documentation for the P2P Bulletin Board standalone application
theme: jekyll-theme-cayman

# Navigation
nav:
  - title: Project Overview
    url: overview.html
  - title: Features
    url: features.html
  - title: Peer-to-Peer Communication
    url: p2p.html
  - title: Getting Started
    url: getting-started.html

# GitHub repository
github:
  is_project_page: true
  repository_url: https://github.com/your-username/p2p-bulletin-board

